#language: rust
sudo: false

os:
  - linux
  - osx

cache:
  cargo: true
  directories:
    - ~/gcc-arm-none-eabi-5_4-2016q3

# If you change this, you must also change README and Common.mk
#rust:
#  - nightly-2016-07-29

    #- curl -sL https://static.rust-lang.org/rustup.sh -o ~/rustup.sh
    #curl https://sh.rustup.rs -sSf | sh

before_script:
  - curl -sL https://sh.rustup.rs -o ~/rustup.sh
  - sh ~/rustup.sh -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup override set nightly-2016-07-29
  - rustc --version
  - cargo --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q3-update/+download/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xvf gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; pwd; ls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$HOME/gcc-arm-none-eabi-5_4-2016q3/bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo install rustfmt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap px4/px4; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc-arm-none-eabi; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      find -path ./extern -prune -o -name '*.rs' -exec rustfmt --write-mode=diff {} +; fi
  - ~/gcc-arm-none-eabi-5_4-2016q3/bin/arm-none-eabi-gcc --version
  - arm-none-eabi-gcc --version
  - make -C boards/storm
  - make -C boards/nrf51dk
  - make -C userland/libtock TOCK_ARCH=cortex-m4
  - make -C userland/examples/blink TOCK_ARCH=cortex-m4

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1ba4725f2c3035cb4966
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
